- name: Install keepassxc with my ini-file
  hosts: Debian-Desktop
  become: false
  
  tasks:
  - name: Install KeePassXC
    become: true
    become_method: sudo
    apt:  name=keepassxc update_cache=yes

  - name: Create a directory with keepassxc.ini if it does not exist
    file:
      path: ~/.config/keepassxc
      state: directory
      recurse: true

  - name: Copy my ini-file in config folder
    copy:
      src: files/keepassxc.ini
      dest: ~/.config/keepassxc/keepassxc.ini