- name: Install docker on debian
  hosts: Debian-Desktop
  become: true
  become_method: sudo

  tasks:
  - name: Install needed packages 
    apt:
      pkg:
        - ca-certificates
        - curl
        - gnupg
      update_cache: true

  - name: Add Docker's official GPG key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: Set up the repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ansible_distribution_release}} stable
      state: present

  - name: Install Docker
    apt:
      pkg:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin 
        - docker-compose-plugin

  - name: Adding {{ansible_facts['env']['SUDO_USER']}} to group docker
    user: 
      name: "{{ansible_facts['env']['SUDO_USER']}}"
      groups:
        - docker
      append: yes

  - name: Restart docker service
    service:
      name: docker
      state: restarted
